// init.js -- สร้างข้อมูลตัวอย่างสำหรับ Lab 03 CRUD Operations

db = db.getSiblingDB("learn_mongo");

// ลบข้อมูลเก่า (ถ้ามี)
db.employees.drop();

// เพิ่มข้อมูลพนักงาน 12 คน
db.employees.insertMany([
  {
    name: "สมชาย ใจดี",
    email: "somchai@company.com",
    department: "Engineering",
    position: "Senior Developer",
    salary: 65000,
    skills: ["JavaScript", "Node.js", "MongoDB"],
    isActive: true,
    joinDate: new Date("2020-03-15"),
  },
  {
    name: "สมหญิง รักเรียน",
    email: "somying@company.com",
    department: "Engineering",
    position: "Junior Developer",
    salary: 35000,
    skills: ["Python", "Django"],
    isActive: true,
    joinDate: new Date("2023-01-10"),
  },
  {
    name: "สมศักดิ์ มั่นคง",
    email: "somsak@company.com",
    department: "Marketing",
    position: "Marketing Manager",
    salary: 55000,
    skills: ["SEO", "Content Marketing", "Google Ads"],
    isActive: true,
    joinDate: new Date("2019-07-01"),
  },
  {
    name: "สมใจ สุขสันต์",
    email: "somjai@company.com",
    department: "HR",
    position: "HR Manager",
    salary: 50000,
    skills: ["Recruitment", "Training"],
    isActive: true,
    joinDate: new Date("2018-11-20"),
  },
  {
    name: "มานี มีสุข",
    email: "manee@company.com",
    department: "Engineering",
    position: "DevOps Engineer",
    salary: 60000,
    skills: ["Docker", "Kubernetes", "AWS"],
    isActive: true,
    joinDate: new Date("2021-05-01"),
  },
  {
    name: "มานะ ขยัน",
    email: "mana@company.com",
    department: "Sales",
    position: "Sales Representative",
    salary: 30000,
    skills: ["Negotiation", "CRM"],
    isActive: true,
    joinDate: new Date("2023-06-15"),
  },
  {
    name: "ปิติ สุขใจ",
    email: "piti@company.com",
    department: "Engineering",
    position: "QA Engineer",
    salary: 42000,
    skills: ["Testing", "Selenium", "Jest"],
    isActive: true,
    joinDate: new Date("2022-02-01"),
  },
  {
    name: "วิภา สวยงาม",
    email: "wipa@company.com",
    department: "Design",
    position: "UI/UX Designer",
    salary: 48000,
    skills: ["Figma", "Adobe XD", "CSS"],
    isActive: true,
    joinDate: new Date("2021-09-10"),
  },
  {
    name: "ชาลี อดทน",
    email: "chalee@company.com",
    department: "Engineering",
    position: "Backend Developer",
    salary: 55000,
    skills: ["Java", "Spring Boot", "PostgreSQL"],
    isActive: false,
    joinDate: new Date("2019-04-01"),
  },
  {
    name: "ดวงใจ ร่าเริง",
    email: "duangjai@company.com",
    department: "Marketing",
    position: "Content Writer",
    salary: 28000,
    skills: ["Writing", "Social Media"],
    isActive: true,
    joinDate: new Date("2023-08-01"),
  },
  {
    name: "ประเสริฐ ยิ่งใหญ่",
    email: "prasert@company.com",
    department: "Engineering",
    position: "Tech Lead",
    salary: 80000,
    skills: ["JavaScript", "React", "Node.js", "MongoDB", "AWS"],
    isActive: true,
    joinDate: new Date("2017-01-15"),
  },
  {
    name: "กมล สงบ",
    email: "kamon@company.com",
    department: "Finance",
    position: "Accountant",
    salary: 38000,
    skills: ["Excel", "SAP"],
    isActive: true,
    joinDate: new Date("2022-04-01"),
  },
]);

print("--- Initialized: 12 employees inserted into learn_mongo.employees ---");
