// init.js -- สร้างข้อมูลตัวอย่างสำหรับ Lab 04 Query Operators

db = db.getSiblingDB("learn_mongo");

// ลบข้อมูลเก่า (ถ้ามี)
db.products.drop();
db.orders.drop();

// สร้าง collection products
db.products.insertMany([
  {
    name: "iPhone 15 Pro",
    category: "smartphone",
    brand: "Apple",
    price: 42900,
    stock: 25,
    rating: 4.8,
    tags: ["5g", "premium", "camera"],
    specs: { storage: "256GB", ram: "8GB", screen: 6.1 },
    colors: ["Natural Titanium", "Blue", "White", "Black"],
    releaseDate: new Date("2023-09-22"),
    isAvailable: true,
  },
  {
    name: "Samsung Galaxy S24",
    category: "smartphone",
    brand: "Samsung",
    price: 32900,
    stock: 40,
    rating: 4.6,
    tags: ["5g", "ai", "camera"],
    specs: { storage: "256GB", ram: "8GB", screen: 6.2 },
    colors: ["Amber Yellow", "Onyx Black", "Marble Gray"],
    releaseDate: new Date("2024-01-17"),
    isAvailable: true,
  },
  {
    name: "MacBook Air M3",
    category: "laptop",
    brand: "Apple",
    price: 44900,
    stock: 15,
    rating: 4.9,
    tags: ["m3", "lightweight", "premium"],
    specs: { storage: "512GB", ram: "16GB", screen: 13.6 },
    colors: ["Midnight", "Starlight", "Silver", "Space Gray"],
    releaseDate: new Date("2024-03-08"),
    isAvailable: true,
  },
  {
    name: "Lenovo ThinkPad X1",
    category: "laptop",
    brand: "Lenovo",
    price: 52900,
    stock: 8,
    rating: 4.5,
    tags: ["business", "lightweight", "premium"],
    specs: { storage: "512GB", ram: "16GB", screen: 14.0 },
    colors: ["Black"],
    releaseDate: new Date("2023-06-15"),
    isAvailable: true,
  },
  {
    name: "iPad Air",
    category: "tablet",
    brand: "Apple",
    price: 24900,
    stock: 30,
    rating: 4.7,
    tags: ["m1", "lightweight", "pencil"],
    specs: { storage: "256GB", ram: "8GB", screen: 10.9 },
    colors: ["Blue", "Purple", "Pink", "Starlight", "Space Gray"],
    releaseDate: new Date("2022-03-18"),
    isAvailable: true,
  },
  {
    name: "Samsung Galaxy Tab S9",
    category: "tablet",
    brand: "Samsung",
    price: 29900,
    stock: 0,
    rating: 4.4,
    tags: ["amoled", "s-pen", "premium"],
    specs: { storage: "256GB", ram: "12GB", screen: 11.0 },
    colors: ["Graphite", "Beige"],
    releaseDate: new Date("2023-08-11"),
    isAvailable: false,
  },
  {
    name: "AirPods Pro 2",
    category: "audio",
    brand: "Apple",
    price: 8990,
    stock: 100,
    rating: 4.8,
    tags: ["noise-cancelling", "wireless", "premium"],
    specs: { battery: "6h", chargingCase: "30h" },
    colors: ["White"],
    releaseDate: new Date("2023-09-22"),
    isAvailable: true,
  },
  {
    name: "Sony WH-1000XM5",
    category: "audio",
    brand: "Sony",
    price: 12900,
    stock: 20,
    rating: 4.7,
    tags: ["noise-cancelling", "wireless", "over-ear"],
    specs: { battery: "30h", driver: "30mm" },
    colors: ["Black", "Silver", "Midnight Blue"],
    releaseDate: new Date("2022-05-20"),
    isAvailable: true,
  },
  {
    name: "Nintendo Switch OLED",
    category: "gaming",
    brand: "Nintendo",
    price: 12900,
    stock: 35,
    rating: 4.6,
    tags: ["portable", "oled", "gaming"],
    specs: { storage: "64GB", screen: 7.0, battery: "9h" },
    colors: ["White", "Neon Red/Blue"],
    releaseDate: new Date("2021-10-08"),
    isAvailable: true,
  },
  {
    name: "Logitech MX Master 3S",
    category: "accessories",
    brand: "Logitech",
    price: 3590,
    stock: 50,
    rating: 4.8,
    tags: ["wireless", "ergonomic", "bluetooth"],
    specs: { battery: "70d", dpi: 8000 },
    colors: ["Graphite", "Pale Gray"],
    releaseDate: new Date("2022-06-01"),
    isAvailable: true,
  },
  {
    name: "ASUS ROG Strix G16",
    category: "laptop",
    brand: "ASUS",
    price: 45900,
    stock: 5,
    rating: 4.3,
    tags: ["gaming", "rtx4060", "premium"],
    specs: { storage: "1TB", ram: "16GB", screen: 16.0 },
    colors: ["Eclipse Gray"],
    releaseDate: new Date("2023-03-01"),
    isAvailable: true,
  },
  {
    name: "Google Pixel 8",
    category: "smartphone",
    brand: "Google",
    price: 24900,
    stock: 0,
    rating: 4.5,
    tags: ["5g", "ai", "camera", "pure-android"],
    specs: { storage: "128GB", ram: "8GB", screen: 6.2 },
    colors: ["Obsidian", "Hazel", "Rose"],
    releaseDate: new Date("2023-10-12"),
    isAvailable: false,
  },
]);

// สร้าง collection orders
db.orders.insertMany([
  {
    orderNo: "ORD-001",
    customer: { name: "สมชาย", email: "somchai@mail.com" },
    items: [
      { product: "iPhone 15 Pro", quantity: 1, price: 42900 },
      { product: "AirPods Pro 2", quantity: 1, price: 8990 },
    ],
    total: 51890,
    status: "delivered",
    paymentMethod: "credit_card",
    orderDate: new Date("2024-01-15"),
  },
  {
    orderNo: "ORD-002",
    customer: { name: "สมหญิง", email: "somying@mail.com" },
    items: [
      { product: "MacBook Air M3", quantity: 1, price: 44900 },
    ],
    total: 44900,
    status: "shipped",
    paymentMethod: "bank_transfer",
    orderDate: new Date("2024-02-20"),
  },
  {
    orderNo: "ORD-003",
    customer: { name: "สมศักดิ์", email: "somsak@mail.com" },
    items: [
      { product: "Logitech MX Master 3S", quantity: 2, price: 3590 },
      { product: "Sony WH-1000XM5", quantity: 1, price: 12900 },
    ],
    total: 20080,
    status: "pending",
    paymentMethod: "credit_card",
    orderDate: new Date("2024-03-01"),
  },
  {
    orderNo: "ORD-004",
    customer: { name: "มานี", email: "manee@mail.com" },
    items: [
      { product: "Samsung Galaxy S24", quantity: 1, price: 32900 },
    ],
    total: 32900,
    status: "cancelled",
    paymentMethod: "promptpay",
    orderDate: new Date("2024-03-05"),
  },
  {
    orderNo: "ORD-005",
    customer: { name: "มานะ", email: "mana@mail.com" },
    items: [
      { product: "iPad Air", quantity: 1, price: 24900 },
      { product: "AirPods Pro 2", quantity: 1, price: 8990 },
      { product: "Logitech MX Master 3S", quantity: 1, price: 3590 },
    ],
    total: 37480,
    status: "delivered",
    paymentMethod: "credit_card",
    orderDate: new Date("2024-01-28"),
  },
]);

print("--- Initialized: 12 products + 5 orders in learn_mongo ---");
