// init.js -- สร้างข้อมูลตัวอย่างสำหรับ Lab 05 Bookstore

db = db.getSiblingDB("bookstore");

db.books.drop();

db.books.insertMany([
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "programming",
    price: 890,
    pages: 464,
    isbn: "978-0132350884",
    description: "A Handbook of Agile Software Craftsmanship",
    publishedYear: 2008,
    inStock: true,
    reviews: [
      {
        user: "สมชาย",
        rating: 5,
        comment: "หนังสือดีมากสำหรับนักพัฒนา",
        createdAt: new Date("2024-01-15"),
      },
      {
        user: "สมหญิง",
        rating: 4,
        comment: "อ่านยากนิดหน่อยแต่เนื้อหาดี",
        createdAt: new Date("2024-02-10"),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Pragmatic Programmer",
    author: "David Thomas",
    genre: "programming",
    price: 1200,
    pages: 352,
    isbn: "978-0135957059",
    description: "Your Journey to Mastery, 20th Anniversary Edition",
    publishedYear: 2019,
    inStock: true,
    reviews: [
      {
        user: "มานะ",
        rating: 5,
        comment: "ต้องอ่านทุกคน",
        createdAt: new Date("2024-03-01"),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Design Patterns",
    author: "Erich Gamma",
    genre: "programming",
    price: 1450,
    pages: 416,
    isbn: "978-0201633610",
    description: "Elements of Reusable Object-Oriented Software",
    publishedYear: 1994,
    inStock: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    genre: "self-help",
    price: 550,
    pages: 320,
    isbn: "978-0735211292",
    description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    publishedYear: 2018,
    inStock: true,
    reviews: [
      {
        user: "วิภา",
        rating: 5,
        comment: "เปลี่ยนชีวิตเลย",
        createdAt: new Date("2024-01-20"),
      },
      {
        user: "ปิติ",
        rating: 4,
        comment: "อ่านง่ายมาก",
        createdAt: new Date("2024-02-05"),
      },
      {
        user: "ดวงใจ",
        rating: 5,
        comment: "แนะนำเลย",
        createdAt: new Date("2024-03-10"),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "history",
    price: 650,
    pages: 498,
    isbn: "978-0062316097",
    description: "A Brief History of Humankind",
    publishedYear: 2015,
    inStock: true,
    reviews: [
      {
        user: "สมศักดิ์",
        rating: 5,
        comment: "มุมมองใหม่เกี่ยวกับมนุษยชาติ",
        createdAt: new Date("2024-01-25"),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    genre: "psychology",
    price: 590,
    pages: 499,
    isbn: "978-0374533557",
    description: "How we think and make decisions",
    publishedYear: 2011,
    inStock: false,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Refactoring",
    author: "Martin Fowler",
    genre: "programming",
    price: 1350,
    pages: 448,
    isbn: "978-0134757599",
    description: "Improving the Design of Existing Code, 2nd Edition",
    publishedYear: 2018,
    inStock: true,
    reviews: [
      {
        user: "ชาลี",
        rating: 4,
        comment: "เนื้อหาดี ตัวอย่างชัดเจน",
        createdAt: new Date("2024-02-15"),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    genre: "fiction",
    price: 420,
    pages: 688,
    isbn: "978-0441013593",
    description: "Science fiction masterpiece",
    publishedYear: 1965,
    inStock: true,
    reviews: [
      {
        user: "มานี",
        rating: 5,
        comment: "นิยายวิทยาศาสตร์ที่ดีที่สุด",
        createdAt: new Date("2024-03-05"),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);

print("--- Initialized: 8 books inserted into bookstore.books ---");
